CREATE TABLE Stock
(
   [ID] NVARCHAR(10) PRIMARY KEY NOT NULL,
   [Name] NVARCHAR(255) NOT NULL
);

CREATE TABLE StockExchange
(
  [ID] INT IDENTITY NOT NULL,
  [Stock] NVARCHAR(10) FOREIGN KEY REFERENCES Stock(ID) NOT NULL,
  [Time] DATETIME NOT NULL,
  [Value] FLOAT NOT NULL
);
